name: cicd
## comment

on:
  # Triggers the workflow only when changes are pushed to the main branch.
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GCP_CLUSTER_NAME: wecloudchatcluster
  GCP_PROJECT_ID: gcp-docker-kubernetes-413600
  GCP_REGION: us-east1-d
  AZ_CONTAINER_REGISTRY: wechatcontainerregistry.azurecr.io
  AZ_CLUSTER_NAME: wecloudchatcluster
  AZ_RESOURCE_GROUP: AS-containers-project-wechat
  DOCKER_TAG: ${{ github.sha }}

jobs:
  check-changed-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Get profile-service changed java files
      id: changed-files-profile-service-java
      uses: tj-actions/changed-files@v41
      with:
        files: |
          profile-service/src/main/java/**
    - name: Get login-service changed java files
      id: changed-files-login-service-java
      uses: tj-actions/changed-files@v41
      with:
        files: |
          login-service/src/main/java/**
    - name: Get chat-service changed java files
      id: changed-files-chat-service-java
      uses: tj-actions/changed-files@v41
      with:
        files: |
          chat-service/src/main/java/**
    - name: Get profile-service changed helm files
      id: changed-files-profile-service-helm
      uses: tj-actions/changed-files@v41
      with:
        files: |
          profile-service/src/main/helm/**
    - name: Get profile-service changed helm-multi-cloud files
      id: changed-files-profile-service-helm-multi-cloud
      uses: tj-actions/changed-files@v41
      with:
        files: |
          profile-service/src/main/helm-multi-cloud/**
    - name: Get login-service changed helm files
      id: changed-files-login-service-helm
      uses: tj-actions/changed-files@v41
      with:
        files: |
          login-service/src/main/helm/**
    - name: Get login-service changed helm-multi-cloud files
      id: changed-files-login-service-helm-multi-cloud
      uses: tj-actions/changed-files@v41
      with:
        files: |
          login-service/src/main/helm-multi-cloud/**
    - name: Get chat-service changed helm files
      id: changed-files-chat-service-helm
      uses: tj-actions/changed-files@v41
      with:
        files: |
          chat-service/src/main/helm/**
    outputs:
      profile-service-java-any-changed: ${{ steps.changed-files-profile-service-java.outputs.any_changed }}
      login-service-java-any-changed: ${{ steps.changed-files-login-service-java.outputs.any_changed }}
      chat-service-java-any-changed: ${{ steps.changed-files-chat-service-java.outputs.any_changed }}
      profile-service-helm-any-changed: ${{ steps.changed-files-profile-service-helm.outputs.any_changed }}
      profile-service-helm-multi-cloud-any-changed: ${{ steps.changed-files-profile-service-helm-multi-cloud.outputs.any_changed }}
      login-service-helm-any-changed: ${{ steps.changed-files-login-service-helm.outputs.any_changed }}
      login-service-helm-multi-cloud-any-changed: ${{ steps.changed-files-login-service-helm-multi-cloud.outputs.any_changed }}
      chat-service-helm-any-changed: ${{ steps.changed-files-chat-service-helm.outputs.any_changed }}

  # Build and push image to GCR and ACR if changes are detected in Java source code
  build-push-image:
    runs-on: ubuntu-latest
    needs: check-changed-files
    # only build and push image when there's java code update
    if: "needs.check-changed-files.outputs.profile-service-java-any-changed == 'true' ||\nneeds.check-changed-files.outputs.login-service-java-any-changed == 'true' || \nneeds.check-changed-files.outputs.chat-service-java-any-changed == 'true'\n"
    steps:
    # Checkout to the repo
    - name: Checkout
      uses: actions/checkout@v4

    ### Build docker images for microservices that have changed ###

    ## profile-service: deploy to both GCP and Azure ##
    - name: Build docker image profile-service
      if: needs.check-changed-files.outputs.profile-service-java-any-changed == 'true'
      run: |
        cd profile-service
        docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/profile-service:${{ env.DOCKER_TAG }} -t ${{ env.AZ_CONTAINER_REGISTRY }}/profile-service:${{ env.DOCKER_TAG }} -f ./src/main/docker/Dockerfile .
    ## login-service: deploy to both GCP and Azure ##
    - name: Build docker image login-service
      if: needs.check-changed-files.outputs.login-service-java-any-changed == 'true'
      run: |
        cd login-service
        docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/login-service:${{ env.DOCKER_TAG }} -t ${{ env.AZ_CONTAINER_REGISTRY }}/login-service:${{ env.DOCKER_TAG }} -f ./src/main/docker/Dockerfile .

    ## chat-service: only deploy to GCP ##
    - name: Build docker image chat-service
      if: needs.check-changed-files.outputs.chat-service-java-any-changed == 'true'
      run: |
        cd chat-service
        docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/chat-service:${{ env.DOCKER_TAG }} -f ./src/main/docker/Dockerfile .

    ### Push docker images to GCR and ACR ###
    ## GCP setup ##
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}

    - name: Configure Docker with gcloud CLI
      run: |
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker gcr.io --quiet

      ## Push Docker images to GCR ##
    - name: Push Docker image profile-service gcp
      if: needs.check-changed-files.outputs.profile-service-java-any-changed == 'true'
      run: |
        docker push gcr.io/${{ env.GCP_PROJECT_ID }}/profile-service:${{ env.DOCKER_TAG }}

    - name: Push Docker image login-service gcp
      if: needs.check-changed-files.outputs.login-service-java-any-changed == 'true'
      run: |
        docker push gcr.io/${{ env.GCP_PROJECT_ID }}/login-service:${{ env.DOCKER_TAG }}

    - name: Push Docker image chat-service gcp
      if: needs.check-changed-files.outputs.chat-service-java-any-changed == 'true'
      run: |
        docker push gcr.io/${{ env.GCP_PROJECT_ID }}/chat-service:${{ env.DOCKER_TAG }}

    ## Azure setup ##
    - name: Azure Container Registry login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZ_CONTAINER_REGISTRY }}
        username: ${{ secrets.AZ_REGISTRY_USERNAME }}
        password: ${{ secrets.AZ_REGISTRY_PASSWORD }}

    - name: Push Docker image profile-service az
      ## Push Docker images to ACR ##
      if: needs.check-changed-files.outputs.profile-service-java-any-changed == 'true'
      run: |
        docker push ${{ env.AZ_CONTAINER_REGISTRY }}/profile-service:${{ env.DOCKER_TAG }}

    - name: Push Docker image login-service az
      if: needs.check-changed-files.outputs.login-service-java-any-changed == 'true'
      run: |
        docker push ${{ env.AZ_CONTAINER_REGISTRY }}/login-service:${{ env.DOCKER_TAG }}


  ### Deploy Microservices to GCP and Azure ###

  # deploy-service-to-gcp:
  #   runs-on: ubuntu-latest
  #   needs:
  #   - check-changed-files
  #   - build-push-image
  #   # deploy if there are updates in Java source code or helm templates
  #   if: "always() &&\n(needs.build-push-image.result == 'success' && needs.check-changed-files.outputs.profile-service-java-any-changed == 'true') ||\n(needs.build-push-image.result == 'success' && needs.check-changed-files.outputs.login-service-java-any-changed == 'true') || \n(needs.build-push-image.result == 'success' && needs.check-changed-files.outputs.chat-service-java-any-changed == 'true') ||\n(needs.build-push-image.result == 'skipped' && needs.check-changed-files.outputs.profile-service-helm-any-changed == 'true') ||\n(needs.build-push-image.result == 'skipped' && needs.check-changed-files.outputs.login-service-helm-any-changed == 'true') ||\n(needs.build-push-image.result == 'skipped' && needs.check-changed-files.outputs.chat-service-helm-any-changed == 'true')\n"
  #   steps:
  #   # Checkout to the repo
  #   - name: Checkout
  #     uses: actions/checkout@v4

  #   - name: update profile deployment
  #     if: needs.check-changed-files.outputs.profile-service-java-any-changed == 'true'
  #     run: |
  #       sed -i 's|image:.*|image: gcr.io/${{ env.GCP_PROJECT_ID }}/profile-service:${{ env.DOCKER_TAG }}|' profile-service/src/main/helm/profile/templates/deployment.yaml

  #   - name: update login deployment
  #     if: needs.check-changed-files.outputs.login-service-java-any-changed == 'true'
  #     run: |
  #       sed -i 's|image:.*|image: gcr.io/${{ env.GCP_PROJECT_ID }}/login-service:${{ env.DOCKER_TAG }}|' login-service/src/main/helm/login/templates/deployment.yaml

  #   # TODO: complete the bash script in `run` with your docker image name and file path
  #   - name: update chat deployment
  #     if: needs.check-changed-files.outputs.chat-service-java-any-changed == 'true'
  #     run: |
  #       sed -i 's|image:.*|image: gcr.io/${{ env.GCP_PROJECT_ID }}/chat-service:${{ env.DOCKER_TAG }}|' chat-service/src/main/helm/chat/templates/deployment.yaml

  #   # We will use Service Account key JSON to authenticate into gcloud for this project
  #   - name: Authenticate to Google Cloud
  #     uses: google-github-actions/auth@v2
  #     with:
  #       credentials_json: ${{ secrets.GCP_SA_KEY }}

  #   - name: Get GKE Credentials
  #     uses: google-github-actions/get-gke-credentials@v2
  #     with:
  #       cluster_name: ${{ env.GCP_CLUSTER_NAME }}
  #       location: ${{ env.GCP_REGION }}
  #       project_id: ${{ env.GCP_PROJECT_ID }}

  #   - name: Deploy profile-service to the cluster with helm
  #     if: "needs.check-changed-files.outputs.profile-service-java-any-changed == 'true' || \n(needs.build-push-image.result == 'skipped' && needs.check-changed-files.outputs.profile-service-helm-any-changed == 'true')\n"
  #     run: |
  #       cd profile-service
  #       helm upgrade --install profile src/main/helm/profile

  #   - name: Deploy login-service to the cluster with helm
  #     if: |
  #       needs.check-changed-files.outputs.login-service-java-any-changed == 'true' ||
  #       (needs.build-push-image.result == 'skipped' && needs.check-changed-files.outputs.login-service-helm-any-changed == 'true')
  #     run: |
  #       cd login-service
  #       helm upgrade --install login src/main/helm/login

  #   - name: Deploy chat-service to the cluster with helm
  #     if: |
  #       needs.check-changed-files.outputs.chat-service-java-any-changed == 'true' ||
  #       (needs.build-push-image.result == 'skipped' && needs.check-changed-files.outputs.chat-service-helm-any-changed == 'true')
  #     run: |
  #       cd chat-service
  #       helm upgrade --install chat src/main/helm/chat

  # deploy-service-to-az:
  #   runs-on: ubuntu-latest
  #   needs:
  #   - check-changed-files
  #   - build-push-image
  #   # deploy if there are updates in Java source code or helm templates
  #   if: "always() &&\n(needs.build-push-image.result == 'success' && needs.check-changed-files.outputs.profile-service-java-any-changed == 'true') ||\n(needs.build-push-image.result == 'success' && needs.check-changed-files.outputs.login-service-java-any-changed == 'true') || \n(needs.build-push-image.result == 'skipped' && needs.check-changed-files.outputs.profile-service-helm-multi-cloud-any-changed == 'true') ||\n(needs.build-push-image.result == 'skipped' && needs.check-changed-files.outputs.login-service-helm-multi-cloud-any-changed == 'true')\n"
  #   steps:
  #   # Checkout to the repo
  #   # ** do not change this code **
  #   - name: Checkout
  #     uses: actions/checkout@v4

  #   # Update deployment.yamls to use the docker image we just pushed for profile-service
  #   - name: update profile deployment
  #     if: needs.check-changed-files.outputs.profile-service-java-any-changed == 'true'
  #     run: |
  #       sed -i 's|image:.*|image: ${{ env.AZ_CONTAINER_REGISTRY }}/profile-service:${{ env.DOCKER_TAG }}|' profile-service/src/main/helm-multi-cloud/profile/templates/deployment.yaml

  #   # Update deployment.yamls to use the docker image we just pushed for login-service
  #   - name: update login deployment
  #     if: needs.check-changed-files.outputs.login-service-java-any-changed == 'true'
  #     run: |
  #       sed -i 's|image:.*|image: ${{ env.AZ_CONTAINER_REGISTRY }}/login-service:${{ env.DOCKER_TAG }}|' login-service/src/main/helm-multi-cloud/login/templates/deployment.yaml

  #   # Use creds to login 
  #   - name: Azure Login
  #     uses: azure/login@v1
  #     with:
  #       creds: ${{ secrets.AZ_CREDENTIALS }}

  #   - name: Azure Container Registry login
  #     uses: azure/docker-login@v1
  #     with:
  #       login-server: ${{ secrets.AZ_CONTAINER_REGISTRY }}
  #       username: ${{ secrets.AZ_REGISTRY_USERNAME }}
  #       password: ${{ secrets.AZ_REGISTRY_PASSWORD }}

  #   - name: Set AKS context
  #     uses: azure/aks-set-context@v3
  #     with:
  #       cluster-name: ${{ env.AZ_CLUSTER_NAME }}
  #       resource-group: ${{ env.AZ_RESOURCE_GROUP }}

  #   - name: Deploy profile-service to the cluster with helm
  #     if: "needs.check-changed-files.outputs.profile-service-java-any-changed == 'true' ||\n(needs.build-push-image.result == 'skipped' && needs.check-changed-files.outputs.profile-service-helm-multi-cloud-any-changed == 'true') \n"
  #     run: |
  #       cd profile-service
  #       helm upgrade --install profile src/main/helm-multi-cloud/profile

  #   - name: Deploy login-service to the cluster with helm
  #     if: |
  #       needs.check-changed-files.outputs.login-service-java-any-changed == 'true' ||
  #       (needs.build-push-image.result == 'skipped' && needs.check-changed-files.outputs.login-service-helm-multi-cloud-any-changed == 'true')
  #     run: |
  #       cd login-service
  #       helm upgrade --install login src/main/helm-multi-cloud/login

